codecov:
  token: fb2782b9-aff0-4977-826a-423d9e245d2b
  branch: master

coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project:
      default:
        target: auto
        if_no_uploads: error
        if_ci_failed: error

    patch:
      default:
        if_no_uploads: error

    changes: true

  ignore:
    - "test/*"

comment:
  layout: "header, diff, changes, uncovered"
  behavior: default
